In [7]:
import numpy as np

Arrays - Introduction

In [9]:
list = [1,2,3,4,5,6,7,8,9,10]
array = np.array ([1,2,3,4,5,6,7,8,9,10])
print(array)
print(list)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
print(list + array)

[ 2  4  6  8 10 12 14 16 18 20]


In [22]:
print ( array*2)
print (array*array)

[ 2  4  6  8 10 12 14 16 18 20]
[  1   4   9  16  25  36  49  64  81 100]


One - dimensional and two dimensional arrays

In [25]:

array1 = np.array({[1,2,3], [4,5,6], [8,9,10]})
print (array1)

TypeError: unhashable type: 'list'

In [48]:
array = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (array [1:8])
print (array [5:])
print (array [:7])
print (array [0:12:2])

[2 3 4 5 6 7 8]
[ 6  7  8  9 10 11 12]
[1 2 3 4 5 6 7]
[ 1  3  5  7  9 11]


In [52]:
zeros=np.zeros(10)
print (zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [53]:
ones=np.ones(5)
print (ones)

[1. 1. 1. 1. 1.]


In [55]:
random=np.random.rand(3,4)
print (random)

[[0.44551736 0.55293175 0.24814242 0.78662691]
 [0.4740786  0.44640272 0.18356741 0.49428385]
 [0.3718732  0.56004454 0.84260346 0.00676458]]


In [58]:
eye=np.eye(8)
print (eye)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [68]:
even = np.arange(6)
print (even)

[0 1 2 3 4 5]


In [70]:
numbers = np.arange (1,20,5)
print (numbers)

[ 1  6 11 16]


In [67]:

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArray= array.reshape(4,3)
print(newArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [72]:
array =np.arange(0,5)
print(array)
print("Subtract :", array -10)  
print("Multiply :", array * 10)  
print("Divide :", array / 10)  
print("Power :", array ** 2)

[0 1 2 3 4]
Subtract : [-10  -9  -8  -7  -6]
Multiply : [ 0 10 20 30 40]
Divide : [0.  0.1 0.2 0.3 0.4]
Power : [ 0  1  4  9 16]


In [75]:
a = np.arange (1,10).reshape (3,3)  
b = np.arange (10,19).reshape (3,3)  
c = np.dot(a,b)
print(c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [77]:
a = np.arange (1,10).reshape (3,3) 
b = np.arange (10,19).reshape (3,3) 
c = np.dot(a,b)
sum =np.sum(c)  
print(sum)

1944


In [78]:
a = np.arange (1,10).reshape (3,3) 
b = np.arange (10,19).reshape (3,3) 
c = np.dot(a,b)
e = np.sum(c,axis =0)
print(e)

[603 648 693]


Homework

In [73]:
array = np.array(10)
print (array)
newArray= array.reshape(3,3)
print(newArray)
condition = np.mod(arr,3)==0
print (condition)

10


ValueError: cannot reshape array of size 1 into shape (3,3)